### ISSUE TITLE
"Message cannot be blank." on post a message

### ISSUE THREAD

**Issue by And0r-** [humhub/humhub-modules-rest#3]
Hi 
When I send a POST to post a message on a container, I get always "Message cannot be blank."

But I have sent a message...
<img width="2230" alt="postman_post_no_message" src="https://user-images.githubusercontent.com/5835294/54480514-cbb4e600-4829-11e9-8436-78437fd3ba4e.png">

Am I doing something wrong or will post not work in the current version?
I use the newest humhub and rest version.

Thanks for your work, the get requests works very well

**Comment by usama-ayaz** [comment]
I went through this one and figured it out that input request for this api is "form-data" instead of "json". We will fix it soon, please check-out the attachment. 
<img width="1008" alt="Screen Shot 2019-06-19 at 7 15 28 PM" src="https://user-images.githubusercontent.com/4687408/59773190-a28f7000-92c6-11e9-8d38-b2d1e3b94af1.png">
