### ISSUE TITLE
Creating CFiles root folder via API

### ISSUE THREAD

**Issue by avillaindesire** [humhub/humhub-modules-rest#45]
It turns out that even if you make the CFiles module a default module when creating a space, the 'root' and 'posted files' folders don't get created until you actually hit the Files URL for the space. I found this a problem since the folder ID is needed for a lot of the CFile APIs. I added some code to create those folders with an API call, but even though it creates the folders, the API returns an internal server error. I can live with it, but I was curious as to why it's returning an error. My code snippets below. Thanks for any guidance!  

`

I added this to create root folder from REST API in the FolderController.php file

    public function actionCreateRoot($containerId)

    {
        $containerRecord = ContentContainer::findOne(['id' => $containerId]);
        if ($containerRecord === null) {
            return $this->returnError(404, 'Content container not found!');
        }

	/** @var ContentContainerActiveRecord $container */
        $container = $containerRecord->getPolymorphicRelation();

        $root = Folder::find()->contentContainer($container)->andWhere(['type' => 'root'])->one();

        if ($root === null) {
            $container->_rootFolder = Folder::initRoot($container);
            return $this->returnSuccess("Root folder created");
        }

	return $this->returnSuccess("Container already has a root folder.");
    }
`

**Comment by luke-** [comment]
@yurabakhtin Can you please take a look here? Usually the Root folders should be created automatically. Ideally also with the API.

**Comment by yurabakhtin** [comment]
@avillaindesire You have the error in the line `$container->_rootFolder = Folder::initRoot($container);` because `$container->_rootFolder` is private and cannot be used as public, and really you should do this there, you can do just `Folder::initRoot($container);`, this will solve your error.
Also the line `Folder::find()->contentContainer($container)->andWhere(['type' => 'root'])->one();` can be replaced with `Folder::getRoot($container)`, so your code may be like:

```php
if (!Folder::getRoot($container)) {
    Folder::initRoot($container);
    return $this->returnSuccess("Root folder created");
}
```

**Comment by yurabakhtin** [comment]
@luke- I find the root and "posted files" folders are created automatically only on `humhub\modules\cfiles\controllers\BaseController::beforeAction()`, i.e. where user opens the browse page of the created space, but if a page like `http://site.address/s/space_name/cfiles/browse` was not opened then the folder will not be created.
It seems we should we create them automatically on creating new space with enabled module cfiles, right?
Also should we do same on call any API cfile endpoint?

**Comment by luke-** [comment]
@yurabakhtin Yes, we should check this everywhere if possible and create the missing folders if necessary.

**Comment by yurabakhtin** [comment]
@luke- PR https://github.com/humhub/humhub-modules-cfiles/pull/105 for module `cfile` - I have implemented to create the default folders on insert new Space/User if the module `cfile` is enabled by default, and also do this on first enabling the module per Space/User.

But I don't think we should do similar on the rest module. As I understand currently it is not possible to create any other folder if the root doesn't exist because here https://github.com/humhub/humhub-modules-rest/blob/master/controllers/cfiles/FolderController.php#L50-L57 we don't allow to create a folder without provided target/parent:

```php
if (empty($params['target_id'])) {
    return $this->returnError(400, 'Target folder id is required!');
}

$targetDir = Folder::findOne(['id' => $params['target_id']]);
if ($targetDir === null) {
    return $this->returnError(404, 'cFiles folder not found!');
}
```

I suggest to allow to create a folder even with empty `target_id`, so in such case we can create the root folder automatically if it doesn't exists by some reason, otherwise use already existing root folder by default for such requests with empty `target_id`. But if the `target_id` is provided but the folder is not found then of course we should return 404='cFiles folder not found!'. Do you agree such solution?

**Comment by avillaindesire** [comment]
@yurabakhtin Thank you for letting me know what I was doing wrong. I'm pretty new to working with PHP & Rest APIs, so that was really helpful! 

I agree with your last message regarding how to handle the rest requests. It would be nice if target_id was optional and the request would default to the root folder if the folder ID was not provided.

**Comment by luke-** [comment]
@yurabakhtin Sounds good. I agree with the solution.

**Comment by yurabakhtin** [comment]
@luke- Ok, done as PR https://github.com/humhub/humhub-modules-rest/pull/46

**Comment by luke-** [comment]
Thanks!
